trigger:
  - dev

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'TFMovies.API/TFMovies.API/TFMovies.API.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
  
  - task: PublishBuildArtifacts@1
  
#  - task: AzureWebApp@1
#    inputs:
#      azureSubscription: 'TechFabric Subscription 1 (3100c099-f7a3-4c34-a1cc-3e921121860a)'
#      appType: 'webApp'
#      appName: 'dev-api-tfmovies'
#      package: '$(Build.ArtifactStagingDirectory)/Output/**/*.zip'
#      deploymentMethod: 'auto'